events {}

http {
  upstream auth  { server auth-service:3001; }
  upstream users { server user-service:3002; }
  upstream tasks { server task-service:3003; }

  server {
    listen 80;
    location /api/auth  { proxy_pass http://auth; }
    location /api/users { proxy_pass http://users; }
    location /api/tasks { proxy_pass http://tasks; }
  }
}
