apiVersion: v1
kind: Secret
metadata:
  name: todo-secrets
  namespace: todo-app
type: Opaque
stringData:
  AUTH_DATABASE_URL: "postgresql://postgres:PASSWORD@auth-db:5432/auth_db"
  USER_DATABASE_URL: "postgresql://postgres:PASSWORD@user-db:5432/user_db"
  TASK_DATABASE_URL: "postgresql://postgres:PASSWORD@task-db:5432/task_db"
  JWT_SECRET: "my_jwt_secret_key_minimum_32_chars"
  JWT_REFRESH_SECRET: "my_refresh_secret_key_minimum_32_chars"
  REDIS_URL: "redis://redis:6379"
  RABBITMQ_URL: "amqp://admin:adminpassword123@rabbitmq:5672"
  MINIO_USER: "minioadmin"
  MINIO_PASS: "minioadmin123"
  SMTP_HOST: "sandbox.smtp.mailtrap.io"
  SMTP_PORT: "2525"
  SMTP_USER: "e7077add4002af"
  SMTP_PASS: "01e0deb424acee"